var math_pad = [
	{"tab_name": "Basic", "buttons": [
		{'desc': 'add', 'cmd': '+', 'disp': '+'},
		{'desc': 'minus', 'cmd': '-', 'disp': '-'},
		{'desc': 'times', 'cmd': '\\\\times', 'disp': '\\times'},
		{'desc': 'dot product', 'cmd': '\\\\cdot', 'disp': '\\cdot'},
		{'desc': 'cross product', 'cmd': '\\\\otimes', 'disp': '\\otimes'},
		{'desc': 'fraction', 'cmd': '\\\\frac', 'disp': '\\frac{\\Box}{\\Box}'},
		{'desc': 'division', 'cmd': '\\\\div', 'disp': '\\div'},
		{'desc': 'equal', 'cmd': '=', 'disp': '='},
		{'desc': 'not equal', 'cmd': '\\\\neq', 'disp': '\\neq'},
		{'desc': 'approximately equal', 'cmd': '\\\\approx', 'disp': '\\approx'},
		{'desc': 'proportional', 'cmd': '\\\\propto', 'disp': '\\propto'},
		{'desc': 'greater than', 'cmd': '\\\\gt', 'disp': '\\gt'},
		{'desc': 'less than', 'cmd': '\\\\lt', 'disp': '\\lt'},
		{'desc': 'greater or equal', 'cmd': '\\\\ge', 'disp': '\\ge'},
		{'desc': 'less or equal', 'cmd': '\\\\le', 'disp': '\\le'},
		{'desc': 'dots', 'cmd': '\\\\ldots', 'disp': '\\ldots'},
		{'desc': 'Pi', 'cmd': '\\\\pi', 'disp': '\\pi'}
	]},
	{"tab_name": "Basic 2", "buttons": [
		{'desc': 'square', 'cmd': 'x^', 'disp': 'x^\\Box'},
		{'desc': 'subscript', 'cmd': 'x_', 'disp': 'x_{\\Box}'},
		{'desc': 'sum', 'cmd': '\\\\sum\tn=0\t \\\\infty \t', 'disp': '\\sum'},
		{'desc': 'product', 'cmd': '\\\\prod\tn=0\tN\t', 'disp': '\\prod'},
		{'desc': 'absolute value', 'cmd': '|', 'disp': '|\ \\Box\ |'},
		{'desc': 'factorial', 'cmd': 'n!', 'disp': 'n!'},
		{'desc': 'square root', 'cmd': '\\\\sqrt', 'disp': '\\sqrt{(\\Box)}'},
		{'desc': 'nth root', 'cmd': '\\\\nthroot', 'disp': '\\sqrt[\\Box]{(\\Box)}'},
		{'desc': 'natural logarithm', 'cmd': '\\\\ln(', 'disp': '\\ln(\\Box)'},
		{'desc': 'logarithmic', 'cmd': '\\\\log_', 'disp': '\\log_{\\Box}()'},
		{'desc': 'exponential', 'cmd': '\\\\exp(x)\t', 'disp': '\\exp(x)'},
		{'desc': 'minimal', 'cmd': '\\\\min', 'disp': '\\min()'},
		{'desc': 'maximal', 'cmd': '\\\\max', 'disp': '\\max()'},
	]},
	{"tab_name": "Set/Logic", "buttons": [
		{'desc': 'empty set', 'cmd': '\\\\varnothing', 'disp': '\\varnothing'},
		{'desc': 'not', 'cmd': '\\\\lnot', 'disp': '\\lnot'},
		{'desc': 'bar', 'cmd': '\\\\bar\tx\t', 'disp': '\\bar x'},
		{'desc': 'and', 'cmd': '\\\\wedge', 'disp': '\\wedge'},
		{'desc': 'or', 'cmd': '\\\\vee', 'disp': '\\vee'},
		{'desc': 'in', 'cmd': '\\\\in', 'disp': '\\in'},
		{'desc': 'union', 'cmd': '\\\\cup', 'disp': '\\cup'},
		{'desc': 'intersection', 'cmd': '\\\\cap', 'disp': '\\cap'},
		{'desc': 'subset', 'cmd': '\\\\subset', 'disp': '\\subset'},
		{'desc': 'subset or equal', 'cmd': '\\\\subseteq', 'disp': '\\subseteq'},
		{'desc': 'not subseteq', 'cmd': '\\\\nsubseteq ', 'disp': '\\nsubseteq'},
		{'desc': 'not in', 'cmd': '\\\\notin', 'disp': '\\notin'},
		{'desc': 'for all', 'cmd': '\\\\forall', 'disp': '\\forall'},
		{'desc': 'exists', 'cmd': '\\\\exists', 'disp': '\\exists'},
		{'desc': 'not exists', 'cmd': '\\\\nexists', 'disp': '\\nexists'},
		{'desc': 'if and only if', 'cmd': '\\\\Leftrightarrow', 'disp': '\\Leftrightarrow'},
		{'desc': 'necessary', 'cmd': '\\\\Leftarrow', 'disp': '\\Leftarrow'},
		{'desc': 'not necessary', 'cmd': '\\\\nLeftarrow', 'disp': '\\nLeftarrow'},
		{'desc': 'sufficient', 'cmd': '\\\\Rightarrow', 'disp': '\\Rightarrow'},
		{'desc': 'not sufficient', 'cmd': '\\\\nRightarrow', 'disp': '\\nRightarrow'}
	]},
	{"tab_name": "Calculus", "buttons": [
		{'desc': 'limit', 'cmd': '\\\\lim_n \\\\rightarrow \\\\infty \t', 'disp': '\\lim'},
		{'desc': 'approach', 'cmd': '\\\\rightarrow', 'disp': '\\rightarrow'},
		{'desc': 'infinity', 'cmd': '\\\\infty', 'disp': '\\infty'},
		{'desc': 'first derivative', 'cmd': 'f\\\'', 'disp': 'f\''},
		{'desc': 'higher order derivative', 'cmd': '\\\\frac d^2 \t\t dx^2 \t\t', 'disp': '\\frac{d^\\Box}{dx^\\Box}'},
		{'desc': 'partial derivative', 'cmd': '\\\\partial/\\\\partial x\t', 'disp': '\\frac{\\partial}{\\partial x}'},
		{'desc': 'integral', 'cmd': '\\\\int_0\t^1\t', 'disp': '\\int_{\\Box}^{\\Box}'},
		{'desc': 'contour integral', 'cmd': '\\\\oint_C\t\t', 'disp': '\\oint'}
	]},
	{"tab_name": "Geometry", "buttons": [
		{'desc': 'angle', 'cmd': '\\\\angle', 'disp': '\\angle'},
		{'desc': 'degree', 'cmd': 'x^\\\\circ\t\t', 'disp': 'x^\\circ'},
		{'desc': 'vector', 'cmd': '\\\\vec ab \t', 'disp': '\\vec{ab}'},
		{'desc': 'perpendicular', 'cmd': '\\\\perp', 'disp': '\\perp'},
		{'desc': 'congruent triangle', 'cmd': '\\\\triangleq', 'disp': '\\triangleq'},
		{'desc': 'parallel', 'cmd': '\\\\parallel', 'disp': '\\parallel'},
		{'desc': 'not parallel', 'cmd': '\\\\nparallel', 'disp': '\\nparallel'},
		{'desc': 'sin', 'cmd': '\\\\sin', 'disp': '\\sin'},
		{'desc': 'cos', 'cmd': '\\\\cos', 'disp': '\\cos'},
		{'desc': 'tan', 'cmd': '\\\\tan', 'disp': '\\tan'},
		{'desc': 'cot', 'cmd': '\\\\cot', 'disp': '\\cot'},
		{'desc': 'csc', 'cmd': '\\\\csc', 'disp': '\\csc'},
		{'desc': 'sec', 'cmd': '\\\\sec', 'disp': '\\sec'},
		{'desc': 'arcsin', 'cmd': '\\\\arcsin', 'disp': '\\arcsin'},
		{'desc': 'arccos', 'cmd': '\\\\arccos', 'disp': '\\arccos'},
		{'desc': 'arctan', 'cmd': '\\\\arctan', 'disp': '\\arctan'}
	]},
	{"tab_name": "Greek/Symbols", "buttons": [
		{'desc': 'alpha', 'cmd': '\\\\alpha', 'disp': '\\alpha'},
		{'desc': 'beta', 'cmd': '\\\\beta', 'disp': '\\beta'},
		{'desc': 'gamma', 'cmd': '\\\\gamma', 'disp': '\\gamma'},
		{'desc': 'delta', 'cmd': '\\\\delta', 'disp': '\\delta'},
		{'desc': 'zeta', 'cmd': '\\\\zeta', 'disp': '\\zeta'},
		{'desc': 'eta', 'cmd': '\\\\eta', 'disp': '\\eta'},
		{'desc': 'theta', 'cmd': '\\\\theta', 'disp': '\\theta'},
		{'desc': 'lambda', 'cmd': '\\\\lambda', 'disp': '\\lambda'},
		{'desc': 'mu', 'cmd': '\\\\mu', 'disp': '\\mu'},
		{'desc': 'nu', 'cmd': '\\\\nu', 'disp': '\\nu'},
		{'desc': 'xi', 'cmd': '\\\\xi', 'disp': '\\xi'},
		{'desc': 'rho', 'cmd': '\\\\rho', 'disp': '\\rho'},
		{'desc': 'sigma', 'cmd': '\\\\sigma', 'disp': '\\sigma'},
		{'desc': 'tau', 'cmd': '\\\\tau', 'disp': '\\tau'},
		{'desc': 'upsilon', 'cmd': '\\\\upsilon', 'disp': '\\upsilon'},
		{'desc': 'phi', 'cmd': '\\\\phi', 'disp': '\\phi'},
		{'desc': 'chi', 'cmd': '\\\\chi', 'disp': '\\chi'},
		{'desc': 'psi', 'cmd': '\\\\psi', 'disp': '\\psi'},
		{'desc': 'ell', 'cmd': '\\\\ell', 'disp': '\\ell'},
		{'desc': 'omega', 'cmd': '\\\\omega', 'disp': '\\omega'},
		{'desc': 'Gamma', 'cmd': '\\\\Gamma', 'disp': '\\Gamma'},
		{'desc': 'Delta', 'cmd': '\\\\Delta', 'disp': '\\Delta'},
		{'desc': 'Theta', 'cmd': '\\\\Theta', 'disp': '\\Theta'},
		{'desc': 'Xi', 'cmd': '\\\\Xi', 'disp': '\\Xi'},
		{'desc': 'Upsilon', 'cmd': '\\\\Upsilon', 'disp': '\\Upsilon'},
		{'desc': 'Phi', 'cmd': '\\\\Phi', 'disp': '\\Phi'},
		{'desc': 'Psi', 'cmd': '\\\\Psi', 'disp': '\\Psi'},
		{'desc': 'Omega', 'cmd': '\\\\Omega', 'disp': '\\Omega'},
		{'desc': 'real numbers', 'cmd': 'R', 'disp': '\\mathbb{R}'},
		{'desc': 'natural numbers', 'cmd': 'N', 'disp': '\\mathbb{N}'},
		{'desc': 'integers', 'cmd': 'Z', 'disp': '\\mathbb{Z}'},
		{'desc': 'rational numbers', 'cmd': 'Q', 'disp': '\\mathbb{Q}'}
	]}
];
