//#define DEBUG_INDEXER

#define MAX_CORPUS_FILE_SZ  (1024 * 1024 * 16)

#define DEFAULT_INDEXER_OUTPUT_DIR "./tmp"

#define UNFREE_CNT_INDEXER_MAINTAIN 1000

#define INDEX_SUPPORT_MATH_WILDCARDS

//#define INDEXD_PARSER_ERROR_LOG
