//#define DEBUG_MEM_POSTING
//#define DEBUG_MEM_POSTING_SMALL_BUF_SZ 63
//#define DEBUG_MEM_POSTING_SHOW_COMPRESS_RATE

#define SYS_MEM_PAGE_SZ 4096
#define MEM_POSTING_BUF_SZ (SYS_MEM_PAGE_SZ + (SYS_MEM_PAGE_SZ >> 1))
