#define SEARCHD_DEFAULT_PORT 8921
#define SEARCHD_DEFAULT_URI  "/search"

//#define DEBUG_PRINT_HTTP_HEAD
//#define DEBUG_SEARCHD
//#define DEBUG_APPEND_RESULTS

#define SEARCHD_HIGHLIGHT_OPEN  "<em class=\"hl\">"
#define SEARCHD_HIGHLIGHT_CLOSE "</em>"

#define SEARCHD_DEFAULT_CACHE_MB 32 /* 32 MB */
