#define SEARCHD_DEFAULT_PORT 8921
#define SEARCHD_DEFAULT_URI  "/search"

#define HIGHLIGHTD_DEFAULT_PORT 8961
#define HIGHLIGHTD_DEFAULT_URI  "/highlight"

//#define DEBUG_APPEND_RESULTS

#define SEARCHD_HIGHLIGHT_OPEN  "<em class=\"hl\">"
#define SEARCHD_HIGHLIGHT_CLOSE "</em>"

#define SEARCHD_DEFAULT_CACHE_MB 32 /* 32 MB */

#define SEARCHD_LOG_FILE "searchd.log"
#define SEARCHD_LOG_ENABLE

#define MAX_ACCEPTABLE_MATH_KEYWORDS 4
#define MAX_ACCEPTABLE_TERM_KEYWORDS 20

//#define DEBUG_JSON_ENCODE_ESCAPE

#define CLUSTER_MASTER_NODE 0
#define CLUSTER_MAX_QRY_BUF_SZ 65530
#define CLUSTER_MAX_RET_RESULTS RANK_SET_DEFAULT_VOL

#define MAX_SEARCHD_RESPONSE_JSON_SZ \
	(MAX_SNIPPET_SZ * RANK_SET_DEFAULT_VOL)
