// #define ENABLE_PRINT_CACHE_TERMS
// #define MAX_PRINT_CACHE_TERMS 128
// #define DEBUG_TERM_POSTLIST_CACHE

#define DEFAULT_MATH_CACHE_SZ (256 MB)
#define DEFAULT_TERM_CACHE_SZ (16 MB)

#define MAX_MATH_CACHE_DIR_LEVEL 6
