// #define ENABLE_PRINT_CACHE_TERMS
// #define MAX_PRINT_CACHE_TERMS 128
// #define DEBUG_TERM_POSTLIST_CACHE

#define DEFAULT_MATH_CACHE_SZ (256 MB)
#define DEFAULT_TERM_CACHE_SZ (16 MB)

#define DEFAULT_CACHE_THRESHOLD (400 KB)
#define DEFAULT_PREFIX_RATIO 0.6f

#define MAX_MATH_CACHE_DIR_LEVEL 32

#define PROPHET_CACHE_LIST "./cache-list.tmp"

//#define DEBUG_MATH_POSTLIST_CACHE

#define MAX_MATH_CACHE_MISS_CNT 49999
