# specify Indri library path from indri-path.mk
# for `make clean' to work, include indri-path.mk
# optionally.
-include indri-path.mk

include ../rules.mk
include ../module.mk

clean:
	@ echo 'clean'
