#define OPTR_INDEX_TREE_DEGREE_VALVE 6
#define OPTR_INDEX_RANK_MAX          3

#define MAX_OPTR_PRINT_DEPTH         2048
#define SYMBOL_ID_VOLUME             UINT16_MAX
#define MAX_FLOAT_STR_LEN            32
#define MAX_GRAMMAR_ERR_STR_LEN      MAX_PARSER_ERR_STR
#define TYPE_MAP_STR_MAX             128
//#define OPTR_HASH_DEBUG

//#define TEX_PARSER_USE_LATEXML
